name: Build and Push

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.8.0" # Specify the Node.js version

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build # Replace with your build command

      - name: Push to GitHub
        run: |
          git config --global user.name 'Josh Marcus'
          git config --global user.email 'joshmarcus85@gmail.com'
          git add -A
          git commit -m "Deploy."
          git push
